# initial soruce: https://docs.docker.com/compose/django/

version: '3'

services:
  web:
    build: .
    command: sh -c "
        /usr/bin/python manage.py makemigrations && \
        /usr/bin/python manage.py migrate && \
        /usr/bin/python manage.py runserver 0.0.0.0:8000 \
        "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
