version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn jugendstadtplan.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
