# initial soruce: https://docs.docker.com/compose/django/

version: '3'

services:
  web:
    build: .
    command: ./manage.sh setup_docker
    volumes:
      - .:/app
    ports:
      - "8000:8000"
