# Generated by Django 3.2.10 on 2021-12-17 22:42

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tags', tagging.fields.TagField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Was macht diesen Ort besonders?')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/pictures/', verbose_name='Bild')),
                ('homepage', models.URLField(blank=True, null=True, verbose_name='Homepage')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='TikTok')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('opening_hours', models.TextField(blank=True, null=True, verbose_name='Öffnungszeiten')),
                ('is_on_placem', models.BooleanField(blank=True, verbose_name='Dieser Ort ist auf PLACEm zu finden')),
                ('is_public', models.BooleanField(default=False, verbose_name='Veröffentlicht')),
            ],
        ),
    ]
