# Generated by Django 3.0.6 on 2020-05-18 23:11

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tags', tagging.fields.TagField(blank=True, max_length=255)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/pictures/', verbose_name='Bild')),
                ('homepage', models.URLField(blank=True, null=True, verbose_name='Internetpräsenz')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('opening_hours', models.TextField(blank=True, null=True, verbose_name='Öffnungszeiten')),
                ('is_public', models.BooleanField(default=False, verbose_name='Veröffentlicht')),
            ],
        ),
    ]
