# Generated by Django 3.1.7 on 2021-03-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='by_or_for',
            field=models.CharField(choices=[('by', 'von Jugendlichen'), ('for', 'für Jugendliche')], default='by', max_length=100, verbose_name='Dieser Ort wird eingetragen...'),
        ),
    ]
