# Generated by Django 3.1.2 on 2020-10-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_on_placem',
            field=models.BooleanField(default=False, verbose_name='Dieser Ort ist auf PLACEm zu finden'),
        ),
    ]
