# Generated by Django 3.0.4 on 2020-03-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='altitude',
        ),
    ]
