# Generated by Django 3.0.5 on 2020-04-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='location',
            name='homepage',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='location',
            name='picture',
            field=models.ImageField(default=None, upload_to='pictures/'),
        ),
    ]
