# Generated by Django 3.0.5 on 2020-04-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200407_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='has_address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='has_homepage',
        ),
        migrations.RemoveField(
            model_name='location',
            name='has_picture',
        ),
        migrations.AddField(
            model_name='location',
            name='opening_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
