# Generated by Django 3.0.5 on 2020-04-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20200411_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
