# Generated by Django 3.0.6 on 2020-05-11 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_location_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.LocationCategory'),
        ),
    ]
